name: Gestion des reptiles

on:
  push:
    branches:
      - main
    paths:
      - "reptiles/**"

  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
    paths:
      - "reptiles/**"

jobs:
  gestion-reptiles:
    runs-on: ubuntu-latest
    steps:
      - name: Message push
        if: github.event_name == 'push'
        run: echo "🦎 Un reptile a été ajouté au zoo"

      - name: Message PR - ouverture
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: echo "🦎 Un nouveau reptile est proposé !"

      - name: Message PR - modification
        if: github.event_name == 'pull_request' && github.event.action == 'edited'
        run: echo "🦎 Les informations d'un reptile ont été modifiées"

      - name: Message PR - update
        if: github.event_name == 'pull_request' && github.event.action == 'synchronize'
        run: echo "🦎 Un reptile a été mis à jour avec de nouvelles informations"
