name: Surveillance des oiseaux

on:
  pull_request:
    branches:
      - main
    paths:
      - "oiseaux/**"

jobs:
  surveillance-oiseaux:
    runs-on: ubuntu-latest
    steps:
      - name: Affichage des informations PR
        run: |
          echo "Titre : ${{ github.event.pull_request.title }}"
          echo "Type d'événement : ${{ github.event_name }}"
          echo "Auteur : ${{ github.actor }}"
